import secrets

from django.conf import settings
from django.db import models


def generate_worker_invite_code(length: int = 10) -> str:
    """Human-friendly code (no ambiguous 0/O, 1/I)."""
    alphabet = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'
    return ''.join(secrets.choice(alphabet) for _ in range(length))


class Profile(models.Model):
    class Role(models.TextChoices):
        ORG_ADMIN = 'org_admin', 'Facility manager'
        WORKER = 'worker', 'Field technician'

    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='profile',
    )
    role = models.CharField(max_length=20, choices=Role.choices, default=Role.WORKER)
    photo = models.ImageField(
        upload_to='profiles/',
        blank=True,
        null=True,
        help_text='Profile photo (shown in the app header).',
    )

    def __str__(self):
        return f'{self.user.username} ({self.get_role_display()})'


class Worker(models.Model):
    class Trade(models.TextChoices):
        PLUMBER = 'plumber', 'Plumber'
        ELECTRICIAN = 'electrician', 'Electrician'
        GENERAL_TECHNICIAN = 'general_technician', 'General technician'

    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='worker',
        null=True,
        blank=True,
    )
    name = models.CharField(max_length=200)
    trade = models.CharField(
        max_length=32,
        choices=Trade.choices,
        default=Trade.GENERAL_TECHNICIAN,
    )
    title = models.CharField(max_length=200, blank=True)
    department = models.CharField(max_length=200, blank=True)
    employee_id = models.CharField(max_length=64, blank=True)
    facility_location = models.CharField(max_length=200, blank=True)
    tasks_completed = models.PositiveIntegerField(default=0)
    avg_resolution_min = models.PositiveIntegerField(default=0)
    reliability = models.DecimalField(max_digits=5, decimal_places=2, default=100)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class WorkerInvitation(models.Model):
    """Pre-registration for field technicians: facility manager sets name and optional email / employee ID; worker redeems with code at signup."""

    invite_code = models.CharField(max_length=32, unique=True, db_index=True)
    email = models.EmailField(
        blank=True,
        help_text='If set, the worker must use this email when signing up.',
    )
    employee_id = models.CharField(
        max_length=64,
        blank=True,
        help_text='If set, the worker must enter this employee ID at signup.',
    )
    name = models.CharField(max_length=200)
    title = models.CharField(max_length=200, blank=True)
    department = models.CharField(max_length=200, blank=True)
    facility_location = models.CharField(max_length=200, blank=True)
    trade = models.CharField(
        max_length=32,
        choices=Worker.Trade.choices,
        blank=True,
        null=True,
        help_text='If set, the technician must sign up with this trade.',
    )
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='worker_invitations_created',
    )
    claimed_at = models.DateTimeField(null=True, blank=True)
    claimed_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='worker_invitations_claimed',
    )

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f'{self.name} ({self.invite_code})'

    def save(self, *args, **kwargs):
        if not self.invite_code:
            for _ in range(20):
                code = generate_worker_invite_code()
                if not WorkerInvitation.objects.filter(invite_code=code).exists():
                    self.invite_code = code
                    break
            else:  # pragma: no cover
                self.invite_code = generate_worker_invite_code(16)
        super().save(*args, **kwargs)


class WorkerPasswordResetCode(models.Model):
    """One-time code generated by a facility manager so a field technician can set a new password without email."""

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='worker_password_reset_codes',
        db_index=True,
    )
    code = models.CharField(max_length=32, unique=True, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    expires_at = models.DateTimeField(db_index=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='worker_password_reset_codes_created',
    )
    used_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f'{self.user_id} ({self.code[:4]}…)'


def generate_unique_password_reset_code() -> str:
    for _ in range(30):
        candidate = generate_worker_invite_code()
        if not WorkerPasswordResetCode.objects.filter(code=candidate).exists():
            return candidate
    return generate_worker_invite_code(20)


class MaintenanceTask(models.Model):
    """Scheduled maintenance work; drives the org calendar and worker-derived tasks."""

    class Recurrence(models.TextChoices):
        NONE = 'none', 'None'
        DAILY = 'daily', 'Daily'
        WEEKLY = 'weekly', 'Weekly'
        MONTHLY = 'monthly', 'Monthly'

    class Color(models.TextChoices):
        BLUE = 'blue', 'Blue'
        GREEN = 'green', 'Green'
        ORANGE = 'orange', 'Orange'
        RED = 'red', 'Red'

    title = models.CharField(max_length=500)
    description = models.TextField(blank=True)
    location = models.CharField(max_length=500, blank=True)
    start = models.DateTimeField()
    duration_minutes = models.PositiveIntegerField(default=60)
    assigned_trade = models.CharField(
        max_length=32,
        choices=Worker.Trade.choices,
        default=Worker.Trade.GENERAL_TECHNICIAN,
        help_text='All technicians with this trade see the task until it is completed.',
    )
    recurrence_type = models.CharField(
        max_length=20,
        choices=Recurrence.choices,
        default=Recurrence.NONE,
    )
    recurrence_end = models.DateField(null=True, blank=True)
    checklist = models.JSONField(default=list)
    color = models.CharField(
        max_length=20,
        choices=Color.choices,
        default=Color.BLUE,
    )

    class Meta:
        ordering = ['start']
        verbose_name = 'Maintenance task'
        verbose_name_plural = 'Maintenance tasks'

    def __str__(self):
        return self.title


class TaskState(models.Model):
    class Status(models.TextChoices):
        SCHEDULED = 'scheduled', 'Scheduled'
        IN_PROGRESS = 'in_progress', 'In progress'
        COMPLETED = 'completed', 'Completed'

    derived_task_id = models.CharField(max_length=255, unique=True, db_index=True)
    status = models.CharField(
        max_length=20,
        choices=Status.choices,
        default=Status.SCHEDULED,
    )
    notes = models.TextField(blank=True)
    checklist_done = models.JSONField(default=dict)
    photo_count = models.PositiveIntegerField(default=0)
    last_saved_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Task state'
        verbose_name_plural = 'Task states'

    def __str__(self):
        return self.derived_task_id
