# Generated by Django 5.2.13 on 2026-04-09 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('derived_task_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('checklist_done', models.JSONField(default=dict)),
                ('photo_count', models.PositiveIntegerField(default=0)),
                ('last_saved_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Task state',
                'verbose_name_plural': 'Task states',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('org_admin', 'Organization admin'), ('worker', 'Worker')], default='worker', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('employee_id', models.CharField(blank=True, max_length=64)),
                ('facility_location', models.CharField(blank=True, max_length=200)),
                ('tasks_completed', models.PositiveIntegerField(default=0)),
                ('avg_resolution_min', models.PositiveIntegerField(default=0)),
                ('reliability', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('start', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('recurrence_type', models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=20)),
                ('recurrence_end', models.DateField(blank=True, null=True)),
                ('checklist', models.JSONField(default=list)),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('orange', 'Orange'), ('red', 'Red')], default='blue', max_length=20)),
                ('assigned_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='workforce.worker')),
            ],
            options={
                'ordering': ['start'],
            },
        ),
    ]
