# Generated by Django 5.2.13 on 2026-04-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, help_text='Profile photo (shown in the app header).', null=True, upload_to='profiles/'),
        ),
    ]
