# Generated by Django 5.2.13 on 2026-04-16 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0007_rename_calendarevent_to_maintenancetask'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='trade',
            field=models.CharField(choices=[('plumber', 'Plumber'), ('electrician', 'Electrician'), ('general_technician', 'General technician')], default='general_technician', max_length=32),
        ),
        migrations.AddField(
            model_name='workerinvitation',
            name='trade',
            field=models.CharField(blank=True, choices=[('plumber', 'Plumber'), ('electrician', 'Electrician'), ('general_technician', 'General technician')], help_text='If set, the technician must sign up with this trade.', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('org_admin', 'Facility manager'), ('worker', 'Field technician')], default='worker', max_length=20),
        ),
    ]
