# Generated by Django 5.2.13 on 2026-04-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0010_worker_invitation_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('worker', 'Worker'), ('org_admin', 'Facility manager')], default='worker', max_length=20),
        ),
        migrations.CreateModel(
            name='TaskEvidencePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('derived_task_id', models.CharField(db_index=True, max_length=255)),
                ('image', models.ImageField(upload_to='task_evidence/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['derived_task_id'], name='workforce_t_derived_37c2f1_idx')],
            },
        ),
    ]
