"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from typing import Any, Dict
from urllib.parse import unquote, urlparse

from django.contrib.messages import constants as msg_constants
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_env_file(path: Path) -> None:
    """Load KEY=value lines from a file into os.environ (does not override existing vars)."""
    if not path.is_file():
        return
    try:
        text = path.read_text(encoding='utf-8')
    except OSError:
        return
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith('#'):
            continue
        if '=' not in line:
            continue
        key, _, value = line.partition('=')
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key and key not in os.environ:
            os.environ[key] = value


# Local secrets: copy .env.example to .env (see README). .env is gitignored.
_load_env_file(BASE_DIR / '.env')

MESSAGE_TAGS = {
    msg_constants.DEBUG: 'secondary',
    msg_constants.INFO: 'info',
    msg_constants.SUCCESS: 'success',
    msg_constants.WARNING: 'warning',
    msg_constants.ERROR: 'danger',
}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret! Set SECRET_KEY in .env (not in git).
SECRET_KEY = (os.environ.get('SECRET_KEY') or '').strip()
if not SECRET_KEY:
    env_path = BASE_DIR / '.env'
    extra = ''
    if env_path.is_file() and env_path.stat().st_size == 0:
        extra = ' Your `.env` file is empty — add a line like SECRET_KEY=... (see .env.example).'
    elif env_path.is_file():
        extra = ' Set SECRET_KEY in `.env` or export it in your shell.'
    raise ImproperlyConfigured(
        'SECRET_KEY is not set. Copy .env.example to .env in the project root and set SECRET_KEY. '
        'Generate one with: python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())".'
        + extra,
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('1', 'true', 'yes')

_allowed = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,testserver')
ALLOWED_HOSTS = [h.strip() for h in _allowed.split(',') if h.strip()]

_csrf = (os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '') or '').strip()
if _csrf:
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf.split(',') if o.strip()]

# HTTPS behind Render / other reverse proxies (set DJANGO_BEHIND_PROXY=1 in production on Render)
if (not DEBUG) and (os.environ.get('DJANGO_BEHIND_PROXY', '').lower() in ('1', 'true', 'yes')):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_X_FORWARDED_HOST = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'workforce',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    *(
        ('whitenoise.middleware.WhiteNoiseMiddleware',)
        if not DEBUG
        else ()
    ),
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'workforce.context_processors.workforce_profile',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# Default: PostgreSQL when ``DATABASE_URL`` or ``POSTGRES_DB`` is set (see .env.example).
# Fallback: SQLite at ``db.sqlite3`` when Postgres is not configured (no extra services).


def _postgres_configured() -> bool:
    if (os.environ.get('DATABASE_URL') or '').strip():
        return True
    if (os.environ.get('POSTGRES_DB') or os.environ.get('PGDATABASE') or '').strip():
        return True
    return False


def _build_postgres_default() -> Dict[str, Any]:
    url = (os.environ.get('DATABASE_URL') or '').strip()
    if url:
        p = urlparse(url)
        if p.scheme not in ('postgres', 'postgresql'):
            raise ImproperlyConfigured(
                f'DATABASE_URL must use postgresql: or postgres: (found scheme {p.scheme!r}).',
            )
        name = (p.path or '/').lstrip('/')
        if not name:
            raise ImproperlyConfigured('DATABASE_URL must include a database name (path after the host).')
        return {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': unquote(name),
            'USER': unquote(p.username) if p.username else '',
            'PASSWORD': unquote(p.password) if p.password else '',
            'HOST': p.hostname or '127.0.0.1',
            'PORT': str(p.port) if p.port else '5432',
        }
    db = (os.environ.get('POSTGRES_DB') or os.environ.get('PGDATABASE') or '').strip()
    if not db:
        raise ImproperlyConfigured('POSTGRES_DB is not set for PostgreSQL.')
    return {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': db,
        'USER': (os.environ.get('POSTGRES_USER') or os.environ.get('PGUSER') or 'postgres').strip(),
        'PASSWORD': (os.environ.get('POSTGRES_PASSWORD') or os.environ.get('PGPASSWORD') or '').strip(),
        'HOST': (os.environ.get('POSTGRES_HOST') or '127.0.0.1').strip() or '127.0.0.1',
        'PORT': (os.environ.get('POSTGRES_PORT') or '5432').strip() or '5432',
    }


def _build_sqlite_default() -> Dict[str, Any]:
    return {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }


if _postgres_configured():
    try:
        import psycopg  # noqa: F401, PLC0415
    except ImportError as exc:
        raise ImproperlyConfigured(
            'PostgreSQL is configured in the environment, but the psycopg package is not installed. '
            'Run: pip install "psycopg[binary]>=3.1" '
            'Or remove DATABASE_URL and POSTGRES_DB to use SQLite (no extra driver).',
        ) from exc
    DATABASES = {'default': _build_postgres_default()}
else:
    DATABASES = {'default': _build_sqlite_default()}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

if not DEBUG:
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }

_mroot = (os.environ.get('MEDIA_ROOT', '') or '').strip()
MEDIA_URL = 'media/'
MEDIA_ROOT = Path(_mroot) if _mroot else (BASE_DIR / 'media')

LOGIN_URL = 'workforce:login'
LOGIN_REDIRECT_URL = 'workforce:home'
LOGOUT_REDIRECT_URL = 'workforce:login'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Upload size limits (profile photos, exports, etc.)
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024
DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024
